hostname: iguideme.local
ingressClass: nginx
image: ghcr.io/uva-fnwi/iguideme
tag: latest

canvasUrl: canvas.instructure.com
clientId: 104410000000000150
authenticateUrl: https://uvadlo-dev.instructure.com/api/lti/authorize_redirect
jwksUrl: https://canvas.instructure.com/api/lti/security/jwks
lmsBackend: Brightspace
brightspaceHost: 178.21.117.23,
brightspacePort: 5433;,
brightspaceDatabase: bds,
brightspaceSearchPath: bds,
brightspaceRest: Persist Security Info=true;

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: iguideme-lti-key
      key: LtiKey
    - name: iguideme-jwt-key
      key: LTI__SigningKey
    - name: iguideme-canvas-token
      key: LMS__Canvas__AccessToken
    - name: iguideme-brightspace-user
      key: LMS__Brightspace__UserID
    - name: iguideme-brightspace-pass
      key: LMS__Brightspace__Password
