hostname: iguideme.local
ingressClass: nginx
image: ghcr.io/uva-fnwi/iguideme
tag: latest

canvasUrl: canvas.instructure.com
clientId: 104410000000000150
authenticateUrl: https://uvadlo-dev.instructure.com/api/lti/authorize_redirect
jwksUrl: https://canvas.instructure.com/api/lti/security/jwks

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: iguideme-lti-key
      key: LtiKey
    - name: iguideme-jwt-key
      key: LTI__SigningKey
    - name: iguideme-canvas-token
      key: Canvas__AccessToken