trigger:
  - deployment

pool: k8s

jobs:
  - job: build
    steps:
      - script: |
          set -euxo pipefail
          docker build -f Dockerfile -t "fnwicr.azurecr.io/iguideme:latest" .
          docker push "fnwicr.azurecr.io/iguideme:latest"
        displayName: Build staging Docker container
        workingDirectory: ./IguideME.Web
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/deployment'))

      - script: |
          set -euxo pipefail
          VERSION="0.${BUILD_BUILDNUMBER}"
          helm package --version "${VERSION}" --app-version "${VERSION}" charts/iguideme
          helm chart save "iguideme-${VERSION}.tgz" "fnwicr.azurecr.io/helm/iguideme:${VERSION}"
          helm chart push "fnwicr.azurecr.io/helm/iguideme:${VERSION}"
        displayName: Build Helm chart and push to registry
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/deployment'))
        env:
          HELM_EXPERIMENTAL_OCI: 1