trigger:
  - master

variables:
  - group: k8s

pool: k8s

jobs:
  - job: build
    steps:
      - script: |
          set -euxo pipefail
          docker build -f Dockerfile -t "fnwicr.azurecr.io/iguideme:latest" .
          docker push "fnwicr.azurecr.io/iguideme:latest"
        displayName: Build Docker container
        workingDirectory: ./IguideME.Web
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

      - script: |
          set -euxo pipefail
          VERSION="0.${BUILD_BUILDNUMBER}"
          helm package --version "${VERSION}" --app-version "${VERSION}" charts/iguideme
          helm chart save "iguideme-${VERSION}.tgz" "fnwicr.azurecr.io/helm/iguideme:${VERSION}"
          helm chart push "fnwicr.azurecr.io/helm/iguideme:${VERSION}"
          curl "https://k8s.datanose.nl/gitops-updater?name=iguideme&secret=${UPDATER_SECRET}&version=${VERSION}"
        displayName: Build Helm chart and push to registry
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          HELM_EXPERIMENTAL_OCI: 1
          UPDATER_SECRET: $(DEPLOY_SECRET)