apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iguideme-data
  namespace: "{{ .Release.Namespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 50Mi