apiVersion: apps/v1
kind: Deployment
metadata:
  name: iguideme
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: iguideme
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: iguideme
        {{- if .Values.azure }}
        aadpodidbinding: iguideme-azure-kv
        {{- end }}
    spec:
      containers:
        - name: iguideme
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: IGUIDEME_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: LMS__Backend
              value: "{{ .Values.lmsBackend }}"
            - name: LMS__Canvas__Url
              value: "{{ .Values.canvasUrl }}"
            - name: LMS__Brightspace__Connection__Host
              value: "{{ .Values.brightspaceHost}}"
            - name: LMS__Brightspace__Connection__Port
              value: "{{ .Values.brightspacePort }}"
            - name: LMS__Brightspace__Connection__Database
              value: "{{ .Values.brightspaceDatabase}}"
            - name: LMS__Brightspace__Connection__SearchPath
              value: "{{ .Values.brightspaceSearchPath}}"
            - name: LMS__Brightspace__Connection__Rest
              value: "{{ .Values.brightspaceRest}}"
            - name: LTI__ClientId
              value: "{{ .Values.clientId }}"
            - name: LTI__AuthenticateUrl
              value: "{{ .Values.authenticateUrl }}"
            - name: LTI__JwksUrl
              value: "{{ .Values.jwksUrl }}"
          envFrom:
            - secretRef:
                name: iguideme-secret
          {{- if .Values.azure }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/etc/secrets"
              readOnly: true
            - name: iguideme-data
              mountPath: "/data"
          {{- end }}

      {{- if .Values.azure }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "iguideme-secretproviderclass"
        - name: iguideme-data
          persistentVolumeClaim:
            claimName: iguideme-data
      {{- end }}
