{{- if .Values.azure }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: iguideme-secretproviderclass
  namespace: "{{ .Release.Namespace }}"
spec:
  provider: azure
  secretObjects:
    - secretName: iguideme-secret
      type: Opaque
      data:
      {{- range .Values.azure.secrets }}
        - objectName: {{ .name }}
          key: {{ .key }}
      {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.azure.clientId }}"
    keyvaultName: "{{ .Values.azure.keyvaultName }}"
    cloudName: AzurePublicCloud
    objects: |
      array:
      {{- range .Values.azure.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret
      {{- end }}
    resourceGroup: "{{ .Values.azure.resourceGroup }}"
    subscriptionId: "{{ .Values.azure.subscriptionId }}"
    tenantId: "{{ .Values.azure.tenantId }}"
  {{- end }}
