FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /code

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:7.0
WORKDIR /code
COPY --from=build-env /code/out .

ENTRYPOINT [ "dotnet", "IguideME.Web.dll" ]
